stages:
  - build
  - deploy

build:
  image: node:12 
  stage: build
  script:
    - npm install
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - /*
  tags:
    - docker
  
deployToDev:
  stage: deploy
  script:
    - docker build . -t 5050-frontend -f dev.Dockerfile 
    - deployFrontend
  only:
    - develop
  tags:
    - 5050dev
