include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml

stages:
  - test
  - build
  - deploy

build:
  image: node:12 
  stage: build
  script:
    - npm install
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - /*
  tags:
    - docker
  
deployToDev:
  stage: deploy
  script:
    - docker build . -t 5050-frontend -f dev.Dockerfile 
    - deployFrontend
  only:
    - develop
  tags:
    - 5050dev
