export default {
  // Checkout Actions
  SET_RAFFLE_ID: 'SET_RAFFLE_ID',
  SET_ORGANIZATION_ID: 'SET_ORGANIZATION_ID',
  SET_ORDER_INFO: 'SET_ORDER_INFO',
  SET_RAFFLE: 'SET_RAFFLE',
  SET_PROGRESSIVE_RAFFLE: 'SET_PROGRESSIVE_RAFFLE',
  SET_ORGANIZATION: 'SET_ORGANIZATION',
  SET_TICKET_PURCHASE_RESPONSE: 'SET_TICKET_PURCHASE_RESPONSE',
  SET_CHECKOUT_ROUTE: 'SET_CHECKOUT_ROUTE',
  RESET_CHECKOUT: 'RESET_CHECKOUT',
  // App Actions
  SET_IS_LOGGED_IN: 'SET_IS_LOGGED_IN',
};
