export default {
  SET_RAFFLE_ID: 'SET_RAFFLE_ID',
  SET_ORGANIZATION_ID: 'SET_ORGANIZATION_ID',
  SET_ORDER_INFO: 'SET_ORDER_INFO',
  SET_TICKET_PURCHASE_RESPONSE: 'SET_TICKET_PURCHASE_RESPONSE',
};
